### ISSUE TITLE
Output error while testing the code

### ISSUE THREAD

**Issue by hspeace** [bryonkucharski/Multiview-3D-VAE-GAN#1]
When I test the code, I output something like test.png in the project
![000](https://user-images.githubusercontent.com/47311266/76535705-40127b80-64b6-11ea-99fc-c396bdd8addf.png)
I think you may have encountered this situation. If you can, please tell me the solution or the steps for your successful test

**Comment by bryonkucharski** [comment]
Which model are you running? How many epochs are you training for? Maybe you could compare the output to what I have in the report https://github.com/bryonkucharski/Multiview-3D-VAE-GAN/blob/master/Final%20Report.pdf. For the 3D-GAN model, I was getting something similar.

**Comment by pingjing233** [comment]
At first, I didn't change it. I trained epochs 200, 600 and 2200  respectively.
Output as
![600](https://user-images.githubusercontent.com/47311266/76678561-09527780-6614-11ea-89e6-546e6ef673c5.png)
Then I put the model (E, E-op, D, D-op,G,G_op)and runed test_3dvaegan.py.
RuntimeError: shape '[32, 3, 224, 224]' is invalid for input of size 1354752
So I changed --batch_size to 9.
Finally, I got the pictures I said. I used 200, 600 and 2200 epochs  of models, but the results were still square.
Have you tested test_3dvaegan.py? Is it the same as the result of train_vae.py?

**Comment by pingjing233** [comment]
> Which model are you running? How many epochs are you training for? Maybe you could compare the output to what I have in the report https://github.com/bryonkucharski/Multiview-3D-VAE-GAN/blob/master/Final%20Report.pdf. For the 3D-GAN model, I was getting something similar.



> Which model are you running? How many epochs are you training for? Maybe you could compare the output to what I have in the report https://github.com/bryonkucharski/Multiview-3D-VAE-GAN/blob/master/Final%20Report.pdf. For the 3D-GAN model, I was getting something similar.

**Comment by hspeace** [comment]
> Which model are you running? How many epochs are you training for? Maybe you could compare the output to what I have in the report https://github.com/bryonkucharski/Multiview-3D-VAE-GAN/blob/master/Final%20Report.pdf. For the 3D-GAN model, I was getting something similar.

At first, I didn't change it. I trained epochs 200, 600 and 2200  respectively.
Output as
![600](https://user-images.githubusercontent.com/47311266/76678561-09527780-6614-11ea-89e6-546e6ef673c5.png)
Then I put the model (E, E-op, D, D-op,G,G_op)and runed test_3dvaegan.py.
RuntimeError: shape '[32, 3, 224, 224]' is invalid for input of size 1354752
So I changed --batch_size to 9.
Finally, I got the pictures I said. I used 200, 600 and 2200 epochs  of models, but the results were still square.
Have you tested test_3dvaegan.py? Is it the same as the result of train_vae.py?

**Comment by bryonkucharski** [comment]
Great. From my experimentation, the results during training were similar but a little better than the results when testing.

**Comment by DJxuelei** [comment]
Hi @pingjing233.I meet the same question as you say, did you sloved it???

**Comment by DJxuelei** [comment]
> > Which model are you running? How many epochs are you training for? Maybe you could compare the output to what I have in the report https://github.com/bryonkucharski/Multiview-3D-VAE-GAN/blob/master/Final%20Report.pdf. For the 3D-GAN model, I was getting something similar.
> 
> At first, I didn't change it. I trained epochs 200, 600 and 2200 respectively.
> Output as
> ![600](https://user-images.githubusercontent.com/47311266/76678561-09527780-6614-11ea-89e6-546e6ef673c5.png)
> Then I put the model (E, E-op, D, D-op,G,G_op)and runed test_3dvaegan.py.
> RuntimeError: shape '[32, 3, 224, 224]' is invalid for input of size 1354752
> So I changed --batch_size to 9.
> Finally, I got the pictures I said. I used 200, 600 and 2200 epochs of models, but the results were still square.
> Have you tested test_3dvaegan.py? Is it the same as the result of train_vae.py?

Hi @pingjing233.I meet the same question as you say, did you sloved it???

**Comment by shradhaGhansiyal** [comment]
I had the same issue. where during testing I was just getting a noise cube and not the correct reconstruction. I later realised that it was due to the incorrect loading of the trained weights. I had used multiple GPUs (DataParallel) while training, and the weights were getting saved in "module.parameter" format, rather than just "parameter". While testing I was using just one GPU (so no DataParallel), and the weights were not getting loaded at all. So, I was basically running the testing with untrained model.

I corrected it by using multiple GPUs in testing as well.

This link helped. [keyerror](https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686)

**Comment by hspeace** [comment]
> I had the same issue. where during testing I was just getting a noise cube and not the correct reconstruction. I later realised that it was due to the incorrect loading of the trained weights. I had used multiple GPUs (DataParallel) while training, and the weights were getting saved in "module.parameter" format, rather than just "parameter". While testing I was using just one GPU (so no DataParallel), and the weights were not getting loaded at all. So, I was basically running the testing with untrained model.
> 
> I corrected it by using multiple GPUs in testing as well.
> 
> This link helped. [keyerror](https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686)

Thank you. It's really a loading problem. I've submitted it in this project
